title: "工程設計學期成果"
description: MATLAB 與 CNN 的成果報告
<!-- theme: jekyll-theme-Architect-->
theme: jekyll-theme-Slate
baseurl: "my-project"
url: "https://h1130239.github.io"

<!-- remote_theme: pmarsceill/just-the-docs-->
collections:
  matlab:
    output: true
    permalink: /matlab/:name
  CNN:
    output: true
    permalink: /CNN/:name
